ishop/AnimalFeed/urls.py
from django.conf.urls import url

from . import views

app_name = 'AnimalFeed'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/edit$', views.CommodityEditView.as_view(), name='commodity_edit'),
    url(r'^(?P<pk>[0-9]+)/$', views.CommodityView.as_view(), name='commodity'),
    url(r'^staff_commodity/$', views.CommodityStaffView.as_view(), name='staff_commodity'),
    url(r'^staff_orders/$', views.OrderStaffView.as_view(), name='staff_orders'),
    url(r'^register/$', views.RegisterFormView.as_view(), name='register'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^confirmation/$', views.OrderConfirmation.as_view(), name='confirmation'),
    url(r'^accepted/$', views.AcceptedOrderView.as_view(), name='accepted_order')
]

ishop/ishop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    url(r'', include('AnimalFeed.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/media/images/favicon.ico')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ishop/AnimalFeed/models.py
from django.db import models
from django.contrib.auth.models import User

class Commodity(models.Model):
    commodity_name = models.CharField(max_length=200)
    commodity_info = models.TextField()
    remained_count = models.IntegerField(default=0)
    cost_per_item = models.FloatField()

    def __str__(self):
        return "{0}".format(self.commodity_name)


class Photos(models.Model):
    commodity = models.ForeignKey(Commodity)
    picture = models.ImageField(upload_to='pictures')

    def __str__(self):
        return "{0} for {1}".format(self.id, self.commodity.commodity_name)


class Order(models.Model):
    with_delivery = models.BooleanField()
    total_cost = models.FloatField()
    creation_time = models.DateTimeField()
    delivery_completion_time = models.DateTimeField()
    delivery_address = models.CharField(max_length=150)
    order_status = models.CharField(max_length=30)
    customer_name = models.CharField(max_length=150)
    customer_phone = models.CharField(max_length=15)

    def __str__(self):
        return "{0} in {1}".format(self.id, self.creation_time)


class OrderPart(models.Model):
    order = models.ForeignKey(Order)
    commodity = models.ForeignKey(Commodity)
    count = models.IntegerField()
    cost_per_one = models.FloatField()

    def __str__(self):
        return "Order {0}: {1} - {2} items per {3}".format(
            self.order.id,
            self.commodity.id,
            self.count,
            self.cost_per_one
        )


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    address = models.CharField(max_length=150)
    phone_number = models.CharField(max_length=15)

ishop/cart/models.py
from django.db import models

# Create your models here.

ishop/cart/forms.py
from django import forms

ishop/AnimalFeed/views.py
from django.utils import timezone
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.http import HttpResponseRedirect
from django.views import generic
from django.views.generic.base import View
from django.views.generic import DetailView
from django.views.generic.edit import FormView
from cart.cart import Cart
from .models import Commodity, OrderPart, Order, Photos
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.shortcuts import render
import re


class RussianLocalization:
    TRANSLATIONS = {
        "The two password fields didn't match.": "Пароль не совпадает с подтверждением.",
        "Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters.":
            "Введите корректное имя пользователя. Имя пользователя может содержать буквы, цифры, и символы @.+-_",
        "This password is too short. It must contain at least 8 characters.":
            "Пароль слишком короткий. Минимальная длина: 8 символов.",
        "This password is too common.":
            "Пароль слишком простой. Пожалуйста, выберите другой пароль.",
        "This password is entirely numeric.":
            "Пароль не может состоять только из цифр.",
        "A user with that username already exists.":
            "Такой пользователь уже существует",
        "Please enter a correct username and password. Note that both fields may be case-sensitive.":
            "Пожалуйста, введите корректные логин и пароль. Оба поля чувствительны к регистру."
    }

    def cut_on_messages(self, all_messages):
        result = []
        for i in all_messages.items():
            if type(i[1]) == type(str):
                result.append(i[1])
            else:
                for j in i[1]:
                    result.append(str(j))
        return result

    def get_element(self, key):
        if key in self.TRANSLATIONS:
            return self.TRANSLATIONS[key]
        return 'Перевод не найден: "{0}". Пожалуйста, сообщите администратору.'.format(key)

    def get_translated_error_message(self, all_messages):
        messages = self.cut_on_messages(all_messages)
        msg = [self.get_element(i) for i in messages]
        result = msg[0]
        for i in range(1, len(msg)):
            result += '<p>' + msg[i] + '</p>'
        return result

LOCALIZATION = RussianLocalization()

class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = "/login/"
    template_name = "AnimalFeed/register.html"

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect('../login')

    def form_invalid(self, form):
        cont = self.get_context_data(form=form)
        if form.errors:
            print(form.errors)
            cont['error_msg'] = LOCALIZATION.get_translated_error_message(form.errors)
        return self.render_to_response(cont)


class LoginFormView(FormView):
    form_class = AuthenticationForm
    template_name = "AnimalFeed/login.html"
    success_url = "/"

    def form_valid(self, form):
        # Получаем объект пользователя на основе введённых в форму данных.
        self.user = form.get_user()

        # Выполняем аутентификацию пользователя.
        login(self.request, self.user)
        return HttpResponseRedirect('../')

    def form_invalid(self, form):
        cont = self.get_context_data(form=form)
        if form.errors:
            cont['error_msg'] = LOCALIZATION.get_translated_error_message(form.errors)
        return self.render_to_response(cont)


class LogoutView(View):
    def get(self, request):
        # Выполняем выход для пользователя, запросившего данное представление.
        logout(request)

        # После чего, перенаправляем пользователя на главную страницу.
        return HttpResponseRedirect("/")


def update_cart(post_dict, cart, erase_previous_value):
    for item in post_dict.items():
        if item[0].startswith('count_') and item[1] and int(item[1]) > 0:
            id = item[0][len('count_'):]
            addition_value = int(item[1])
            obj = Commodity.objects.get(id=id)
            if obj:
                cart.update(id, obj.commodity_name, obj.cost_per_item, addition_value, erase_previous_value)


class IndexView(generic.ListView):
    template_name = 'AnimalFeed/index.html'

    def get_context_data(self, **kwargs):
        context = dict()
        context['commodities'] = self.get_queryset()
        return context

    def get_queryset(self):
        return Commodity.objects.order_by('commodity_name')

    def post(self, request):
        return self.get(request)


class OrderConfirmation(generic.ListView):
    template_name = 'AnimalFeed/cart.html'

    def get_chosen_items(self, cart):
        keys = (i for i in filter(lambda i: re.match(r'\d+', i),cart))
        all_items = [(i, cart[i]['name'], cart[i]['quantity'], cart[i]['cost_per_one']) for i in keys]
        all_items.sort()
        return all_items

    def get_total_cost(self, request):
        c = Cart(request)
        total_cost = 0
        for item in filter(lambda x: re.match(r'\d+', x[0]) is not None, c.cart.items()):
            total_cost += item[1]['quantity'] * item[1]['cost_per_one']
        return total_cost

    def get_context_data(self, error_msg='', delivery_address='', customer_name='', phone=''):
        context = dict()
        context['error_msg'] = error_msg
        context['chosen'] = self.get_chosen_items(Cart(self.request).cart)
        context['delivery_address'] = delivery_address
        context['customer_name'] = customer_name
        context['customer_phone'] = phone
        context['default_cost'] = self.get_total_cost(self.request)
        return context

    def get_queryset(self):
        pass

    def check_cart(self, request):
        c = Cart(request)
        total_cost = 0
        for item in filter(lambda x: re.match(r'\d+', x[0]) is not None, c.cart.items()):
            quantity = item[1]['quantity']
            if quantity < 0:
                return total_cost, 'Попытка заказать отрицательное количество товара "{0}".'.format(item[1]['name'])
            id = item[0]
            obj = Commodity.objects.get(id=id)
            if not obj:
                return total_cost, 'Неверный id товара. Пожалуйста, напишите администратору.'
            if quantity > obj.remained_count:
                return total_cost, 'Заказ невозможен, на складе недостаточно товара "{0}".'.format(item[1]['name'])
            total_cost += quantity * obj.cost_per_item
        if total_cost == 0:
            return total_cost, 'Отправлен пустой заказ.'
        return total_cost, ''

    def get(self, request, **kwargs):
        auth_error =''
        if not request.user.is_authenticated():
            auth_error = 'Для оформления заказа нужно <a href="{0}">Авторизоваться</a>'.format('/login')
        cart = Cart(request).cart
        return render(request, self.template_name,
                      self.get_context_data(
                          error_msg=auth_error,
                          customer_name=cart['customer_name'],
                          delivery_address=cart['customer_address'],
                          phone=cart['customer_phone']
                      ))

    def page_with_error(self, request, error_message):
        return render(request, self.template_name,
                      self.get_context_data(
                          error_msg=error_message,
                          delivery_address=request.POST['delivery_address'],
                          customer_name=request.POST['customer_name'],
                          phone=request.POST['customer_phone']
                      ))

    def save_order(self, cart, total_cost, with_delivery, delivery_address, customer_name, customer_phone):
        new_order = Order(
            with_delivery=with_delivery,
            total_cost=total_cost,
            creation_time=timezone.now(),
            customer_name=customer_name,
            delivery_address=delivery_address,
            delivery_completion_time=timezone.now(),
            customer_phone=customer_phone,
            order_status='Создан'
        )
        new_order.save()

        for item in filter(lambda x: re.match(r'\d+', x[0]) is not None, cart.cart.items()):
            quantity = item[1]['quantity']
            id = item[0]

            obj = Commodity.objects.get(id=id)

            op = OrderPart(
                commodity_id=id,
                cost_per_one=obj.cost_per_item,
                count=quantity,
                order=new_order
            )
            op.save()

            obj.remained_count -= quantity
            obj.save()

        cart.cart.clear()

    def post(self, request):
        delivery_address = request.POST['delivery_address']
        customer_name = request.POST['customer_name']
        customer_phone = request.POST['customer_phone']

        cart = Cart(request)
        cart.save_parameters(
            customer_name=customer_name, customer_phone=customer_phone, customer_address=delivery_address)

        update_cart(request.POST, cart, True)
        if not request.user.is_authenticated():
            return self.page_with_error(request, 'Для оформления заказа нужно <a href="{0}">Авторизоваться</a>'.format('/login'))
        total_cost, error_message = self.check_cart(request)
        if error_message:
            return self.page_with_error(request, error_message)

        if not re.match(r'^\+?[0-9]+$', customer_phone):
            return self.page_with_error(request, 'Введите номер телефона в формате +79123456789')

        with_delivery = False
        if delivery_address:
            with_delivery = True
        else:
            delivery_address = 'Без доставки'

        self.save_order(cart, total_cost, with_delivery, delivery_address, customer_name, customer_phone)

ishop/cart/views.py
from django.shortcuts import render

ishop/AnimalFeed/templates/AnimalFeed/acceptedOrder.html
{% extends 'AnimalFeed/base.html' %}

{% block title %}Заказ подтверждён{% endblock %}

{% block content %}
    Спасибо за заказ. Мы позвоним вам в ближайшее время.
    <a href="{% url 'AnimalFeed:index' %}">На главную страницу</a>
{% endblock %}

ishop/AnimalFeed/templates/AnimalFeed/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <link rel="icon" type="image/ico" href="../../../media/images/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Интернет-магазин кормов для животных artkorm.ru{% endblock %}</title>

    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/jquery.js"></script>
    <!-- Bootstrap Core CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/heroic-features.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>
        html {
            position: relative;
            min-height: 100%;
        }

        body {
            /* Отступ снизу, по высоте футера */
            margin-bottom: 30px !important;
        }

        .footer {
            position: absolute;
            bottom: 0;
            /* Фиксированная высота футера */
            height: 30px;
        }
    </style>
    {% block scripts %}{% endblock %}
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">artkorm.ru</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <a href="{% url 'AnimalFeed:confirmation' %}">Оформить заказ</a>
                </li>
                {% if user.is_authenticated %}
                    {% if user.is_staff %}
                        <li>
                            <a href="{% url 'AnimalFeed:staff_orders' %}">Список заказов</a>
                        </li>
                        <li>
                            <a href="{% url 'AnimalFeed:staff_commodity' %}">Список товаров</a>
                        </li>
                    {% endif %}
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li>
                        {% if user.is_staff %}
                            <a href="/admin">Здравствуйте, {{ user.username }}</a>
                        {% else %}
                            <a>Здравствуйте, {{ user.username }}</a>
                        {% endif %}
                    </li>
                    <li>
                        <a href="{% url 'AnimalFeed:logout' %}">Выход</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'AnimalFeed:login' %}">Войти</a>
                    </li>
                    <li>
                        <a href="{% url 'AnimalFeed:register' %}">Зарегистрироваться</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Page Content -->
<div class="container">
    <br>
    <br>
    <br>

    {% if accept_msg %}
        <div class="alert alert-success" role="alert">
            {% autoescape off %}
                {{ accept_msg }}
            {% endautoescape %}
        </div>
    {% endif %}
    {% if error_msg %}
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only"></span>
            {% autoescape off %}
                {{ error_msg }}
            {% endautoescape %}
        </div>
    {% endif %}
    {% block content %}{% endblock %}

    <!-- Footer -->
    <footer class="footer">
        <p>Copyright &copy; artkorm.ru 2017</p>
    </footer>
</div>

</body>

</html>

ishop/AnimalFeed/templates/AnimalFeed/cart.html
{% extends 'AnimalFeed/base.html' %}

{% block title %}Подтверждение заказа{% endblock %}

{% block scripts %}
    <script>
        function reloadCost() {
            var total_cost = 0.0;
            var list = document.getElementsByClassName('cartItem');
            for (var i = 0; i < list.length; i++) {
                var count = parseInt(list[i].getElementsByTagName('input')[0].value);
                var cost_per_one = parseFloat(list[i].getElementsByTagName('label')[0].innerHTML);
                total_cost += cost_per_one * count;
            }

            var result_label = document.getElementsByClassName('costLabel')[0];
            result_label.innerHTML = "Общая сумма: " + total_cost.toString() + "руб.";
        }
    </script>
{% endblock %}

{% block content %}
    {% if chosen %}
        <form method="POST">
            {% csrf_token %}
            <div class="list-group">
                {% for id, name, val, cpi in chosen %}
                    <div class="cartItem">
                        <h1>{{ name }}</h1>
                        Стоимость: <label>{{ cpi }}</label><br>
                        <input type='number' class="form-control" id='count' name='count_{{ id }}' min='0'
                               value='{{ val }}' onchange="reloadCost()"/>
                    </div>
                {% endfor %}
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label col-form-label-sm costLabel">{{ default_cost }}</label>
            </div>

            <div class="form-group row">
                <label for="smFormGroupInput" class="col-sm-2 col-form-label col-form-label-sm">Ваше имя</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form-control-sm" id="customer_name"
                           name="customer_name" value="{{ customer_name }}">
                </div>
            </div>

            <div class="form-group row">
                <label for="smFormGroupInput" class="col-sm-2 col-form-label col-form-label-sm">Ваш номер
                    телефона</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form-control-sm" id="customer_phone"
                           name="customer_phone" value="{{ customer_phone }}">
                </div>
            </div>

            <div class="form-group row">
                <label for="smFormGroupInput" class="col-sm-2 col-form-label col-form-label-sm">Адрес доставки</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form-control-sm" id="delivery_address"
                           name="delivery_address" value="{{ delivery_address }}">
                </div>
            </div>

            <br><input type='submit' class="btn btn-primary" value="Оформить заказ."/>
        </form>
    {% else %}
        <p>Вы пока ничего не выбрали.</p>
    {% endif %}
{% endblock %}

ishop/AnimalFeed/templates/AnimalFeed/commodity.html
{% extends 'AnimalFeed/base.html' %}

{% block title %}{{ Commodity.commodity_name }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h1>{{ Commodity.commodity_name }}</h1>
            {% autoescape off %}
                {{ Commodity.commodity_info }}
            {% endautoescape %}
            <p>
                Осталось на складе: {{ Commodity.remained_count }}<br>
                Цена: {{ Commodity.cost_per_item }} руб.
            </p>
            <form method="POST">
                {% csrf_token %}
                <div class="col-md-2">
                    <input type='number' value='1' min='0' max='{{ Commodity.remained_count }}' class="form-control"
                           id='count'
                           name='count_{{ Commodity.id }}'/>
                </div>
                <div class="col-md-2">
                    <input type='submit' class="btn btn-primary" value="В корзину"/>
                </div>
            </form>
            <p>
                {% if user.is_staff %}
                    <a href="/{{ Commodity.id }}/edit">Редактировать</a>
                {% endif %}
            </p>
        </div>
        <div class="col-md-4">
            {% for img in images %}
                <img src="{{ img.picture.url }}" width="100%">
            {% endfor %}
        </div>
    </div>
{% endblock %}

ishop/AnimalFeed/templates/AnimalFeed/commodityEdit.html
{% extends "AnimalFeed/base.html" %}

{% block title %}Редактирование страницы товара{% endblock %}

{% block content %}
<h1>{{ Commodity.commodity_name }}</h1>
<form method="POST">
    {% csrf_token %}
    <textarea class="form-control" id="exampleTextarea" rows="3" name="new_info">{{ Commodity.commodity_info }}</textarea>
    <input class="btn btn-default" type="submit" value="Сохранить изменения"/>
</form>
{% endblock %}

ishop/AnimalFeed/templates/AnimalFeed/index.html
{% extends 'AnimalFeed/base.html' %}

{% block title %}Интернет-магазин кормов для животных artkorm.ru{% endblock %}

{% block content %}
    <header class="jumbotron hero-spacer">
        <h3>Интернет-магазин кормов для животных artkorm.ru</h3>
    </header>
    <div class="list-group">
        {% for c in commodities %}
        <a href="{{ c.id }}" class="list-group-item">
            <h4 class="list-group-item-heading">{{c.commodity_name}}</h4>
            <p>Цена за 1шт.: {{ c.cost_per_item }}</p>
            <p>Осталось на складе: {{ c.remained_count }}</p>
        </a>
        {% endfor %}
    </div>
{% endblock %}

ishop/AnimalFeed/templates/AnimalFeed/login.html
{% extends "AnimalFeed/base.html" %}

{% block title %}Вход{% endblock %}

{% block content %}
    <h1>Вход</h1>

    <form role="form" action="" method="post" class="registration-form">
        {% csrf_token %}
        <div class="form-group">
            <label>Имя пользователя</label>
            {% if form.instance.some_field %}
                <input type="text" name="username" class="form-username form-control"
                       id="id_username" value="{{ form.instance.username }}" required>
            {% else %}
                <input type="text" name="username" class="form-username form-control"
                       id="id_username" value="{{ form.data.username }}" required>
            {% endif %}
        </div>
        <div class="form-group">
            <label>Пароль</label>
            <input type="password" name="password" class="form-password form-control"
                   id="id_password" required>
        </div>
        <button type="submit" class="btn btn-primary">Войти!</button>
    </form>
{% endblock %}

ishop/AnimalFeed/templates/AnimalFeed/register.html
{% extends "AnimalFeed/base.html" %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <h1>Регистрация</h1>
    <form role="form" action="" method="post" class="registration-form">
        {% csrf_token %}
        <div class="form-group">
            <label>Имя пользователя</label>
            {% if form.instance.some_field %}
                <input type="text" name="username" class="form-username form-control"
                       id="id_username" value="{{ form.instance.username }}" required>
            {% else %}
                <input type="text" name="username" class="form-username form-control"
                       id="id_username" value="{{ form.data.username }}" required>
            {% endif %}

        </div>
        <div class="form-group">
            <label>Пароль</label>
            <input type="password" name="password1" class="form-password form-control"
                   id="id_password1" required>
        </div>
        <div class="form-group">
            <label>Подтверждение пароля</label>
            <input type="password" name="password2" class="form-password form-control"
                   id="id_password2" required>
        </div>
        <button type="submit" class="btn btn-primary">Зарегистрироваться!</button>
    </form>
{% endblock %}

ishop/AnimalFeed/templates/AnimalFeed/staffCommodity.html
{% extends "AnimalFeed/base.html" %}

{% block title %}Интернет магазин комбикорм.{% endblock %}

{% block content %}

    <form method="POST">
        {% csrf_token %}
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">Редактирование товаров</div>

            <table class="table">
                <tr>
                    <td>
                        Название
                    </td>
                    <td>
                        Остаток на складе
                    </td>
                    <td>
                        Стоимость единицы
                    </td>
                </tr>
                {% for c in commodities %}
                    <tr>
                        <td>
                            <input type="text" class="form-control" value="{{ c.commodity_name }}" id="name" name="name_{{ c.id }}">
                        </td>
                        <td>
                            <input type="number" class="form-control" min="0" max="100000" value="{{ c.remained_count }}" id="rem"
                                   name="rem_{{ c.id }}">
                        </td>
                        <td>
                            <input type="number" class="form-control" mid="0" max="100000" value="{{ c.cost_per_item }}" id="cpi"
                                   name="cpi_{{ c.id }}">
                        </td>
                    </tr>
                {% endfor %}
                <tr>
                    <td>
                        <input type="text" class="form-control" id="new_name" name="new_name">
                    </td>
                    <td>
                        <input type="number" class="form-control" min="0" max="100000" value="{{ c.remained_count }}" id="new_remained_count"
                               name="new_remained_count">
                    </td>
                    <td>
                        <input type="number" class="form-control" min="0" max="100000" value="{{ c.cost_per_item }}" id="new_cost"
                               name="new_cost">
                    </td>
                </tr>
            </table>
            <input type="submit" class="btn btn-primary" value="Изменить данные">
        </div>
    </form>
{% endblock %}

ishop/AnimalFeed/templates/AnimalFeed/staffOrders.html
{% extends "AnimalFeed/base.html" %}

{% block title %}Заказы{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">Лист заказов</div>

            <table class="table">
                <tr>
                    <td>
                        Номер заказа
                    </td>
                    <td>
                        Имя заказчика
                    </td>
                    <td>
                        Адрес доставки
                    </td>
                    <td>
                        Статус
                    </td>
                </tr>
                {% for order in orders %}
                    <tr>
                        <td>
                            {{ order.id }}
                        </td>
                        <td>
                            {{ order.customer_name }}
                        </td>
                        <td>
                            {{ order.delivery_address }}
                        </td>
                        <td>
                            <input type="text" class="form-control" value="{{ order.order_status }}" id="status"
                                   name="status_{{ order.id }}">
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <input type="submit" class="btn btn-primary" value="Сохранить изменения">
    </form>
{% endblock %}